/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AttendanceNFT } from './AttendanceNFT.js';
export * as factories from './factories/index.js';
export { AttendanceNFT__factory } from './factories/AttendanceNFT__factory.js';